[font]
size = 15.0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Search"
mods = "Control"

[scrolling]
history = 100000

[window.padding]
x = 7
y = 5
