[font]
size = 12.0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Search"
mods = "Control"

[scrolling]
history = 100000

[window.padding]
x = 7
y = 5

[colors.primary]
# background = "#1e1e1e"
# foreground = "#d4d4d4"

[colors.normal]
# black   = "#000000"
# red     = "#cd3131"
green   = "#23d18b"
# yellow  = "#e5e510"
# blue    = "#2472c8"
# magenta = "#bc3fbc"
# cyan    = "#11a8cd"
# white   = "#e5e5e5"

[colors.bright]
# black   = "#666666"
# red     = "#f14c4c"
# green   = "#23d18b"
# yellow  = "#f5f543"
# blue    = "#3b8eea"
# magenta = "#d670d6"
# cyan    = "#29b8db"
# white   = "#ffffff"
